name: Release
on:
  workflow_dispatch:

jobs:
  empower-plant-release:
    runs-on: ubuntu-latest
    name: 'Release a new Android Empower Plant version'
    steps:
      - uses: actions/checkout@v4
      - name: Run Deploy Script
        run: ./github_release.sh
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
